export const UPDATE_INTERACTION_REQUEST = 'UPDATE_INTERACTION_REQUEST'
export const UPDATE_INTERACTION_SUCCESS = 'UPDATE_INTERACTION_SUCCESS'
export const UPDATE_INTERACTION_FAIL = 'UPDATE_INTERACTION_FAIL'

export const RECOMMEND_REQUEST = 'RECOMMEND_REQUEST'
export const RECOMMEND_SUCCESS = 'RECOMMEND_SUCCESS'
export const RECOMMEND_FAIL = 'RECOMMEND_FAIL'

export const RECOMMEND_PRODUCT_REQUEST = 'RECOMMEND_PRODUCT_REQUEST'
export const RECOMMEND_PRODUCT_SUCCESS = 'RECOMMEND_PRODUCT_SUCCESS'
export const RECOMMEND_PRODUCT_FAIL = 'RECOMMEND_PRODUCT_FAIL'

export const RECOMMEND_CATEGORY_PRODUCT_REQUEST =
  'RECOMMEND_CATEGORY_PRODUCT_REQUEST'
export const RECOMMEND_CATEGORY_PRODUCT_SUCCESS =
  'RECOMMEND_CATEGORY_PRODUCT_SUCCESS'
export const RECOMMEND_CATEGORY_PRODUCT_FAIL = 'RECOMMEND_CATEGORY_PRODUCT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
