export const UPDATE_INTERACTION_REQUEST = 'UPDATE_INTERACTION_REQUEST'
export const UPDATE_INTERACTION_SUCCESS = 'UPDATE_INTERACTION_SUCCESS'
export const UPDATE_INTERACTION_FAIL = 'UPDATE_INTERACTION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
